objects/OpportunityLineItem.object
<CustomObject><fields>
        <fullName>Revenue_Months__c</fullName>
        <label>Revenue Months</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Revenue_Projection_Method__c</fullName>
        <label>Revenue Projection Method</label>
        <picklist>
            <picklistValues>
                <fullName>Straight Line</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Revenue_Start_Date__c</fullName>
        <label>Revenue Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds></CustomObject>

objects/Revenue_Schedule__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Revenue Schedule</label><nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Revenue Schedules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/CLS_CustomScheduler.cls
public class CLS_CustomScheduler {
    
    private Opportunity opp;  
    public List<OpportunityLineItem> oliList {get;set;}
    public Map<Opportunity,Revenue_Schedule__c> oppRevenueMap {get;set;}
    public CLS_CustomScheduler(ApexPages.StandardController controller){
        
        opp = (Opportunity)controller.getRecord(); 
        
        this.oliList = [select Id, Name, Revenue_Months__c, Revenue_Projection_Method__c, Revenue_Start_Date__c
                        from OpportunityLineItem where opportunityId =: opp.id]; 
    }
    
    public PageReference save(){
        update oliList;
        PageReference prevPage = new PageReference('/' + opp.Id);
        return prevPage;
    }
    public PageReference cancel(){
        PageReference prevPage = new PageReference('/' + opp.Id);
        return prevPage;
    }
}