objects/Revenue_Schedule__c.object
<CustomObject><fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Revenue_Amount__c</fullName>
        <label>Revenue Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Revenue_Schedule_Date__c</fullName>
        <label>Revenue Schedule Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Revenue_Schedule_Status__c</fullName>
        <label>Revenue Schedule Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <length>30</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Weighted_Revenue_Amount__c</fullName>
        <label>Weighted Revenue Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Revenue Schedule</label><nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Revenue Schedules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/CLS_RevScheduleEdit.cls
public class CLS_RevScheduleEdit {
    
    private Opportunity opp;  
    public List<Revenue_Schedule__c> rsList {get;set;}
    public Map<Opportunity,Revenue_Schedule__c> oppRevenueMap {get;set;}
    public CLS_RevScheduleEdit(ApexPages.StandardController controller){
        
        opp = (Opportunity)controller.getRecord(); 
        this.rsList = [Select Id, Name, Opportunity__c, Revenue_Amount__c, Revenue_Schedule_Date__c,
                       Revenue_Schedule_Status__c, Revenue_Type__c, Weighted_Revenue_Amount__c
                       from Revenue_Schedule__c where Opportunity__c =:opp.Id];
    }
    public PageReference save(){
        update rsList;
        PageReference prevPage = new PageReference('/' + opp.Id);
        return prevPage;
    }
    public PageReference cancel(){
        PageReference prevPage = new PageReference('/' + opp.Id);
        return prevPage;
    }
    
}